# Bun Configuration for WeMake MCP Enterprise Monorepo

# Install configuration
[install]
# Use exact versions for enterprise stability
exact = true

# Registry configuration
registry = "https://registry.npmjs.org/"

# Development server configuration
[dev]
# Enable hot module replacement
hmr = true

# Development server port
port = 3000

# Build configuration
[build]
# Target ES2022 for modern runtime compatibility
target = "ESNext"

# Enable source maps for debugging
sourcemap = true

# Minify for production builds
minify = true