# Bun Configuration for WeMake MCP Enterprise Monorepo

[install]
exact = true
registry = "https://registry.npmjs.org"

[install.scopes]
wemake.cx = { token = "$npm_token", url = "https://registry.npmjs.org" }

[dev]
hmr = true
port = 3000

[build]
target = "ESNext"
sourcemap = true
minify = true

[test]
root = "."
coverage = true
preload = ["./test-setup.ts"]
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }
coveragePathIgnorePatterns = ["node_modules/**", "dist/**", "coverage/**"]