# Bun Configuration for WeMake MCP Enterprise Monorepo

# Install configuration
[install]
# Use exact versions for enterprise stability
exact = true

# Registry configuration
registry = "https://registry.npmjs.org"

[install.scopes]

# Registry with token
wemake.cx = { token = "$npm_token", url = "https://registry.npmjs.org" }

# Development server configuration
[dev]
# Enable hot module replacement
hmr = true

# Development server port
port = 3000

# Build configuration
[build]
# Target ESNext for modern runtime compatibility
target = "ESNext"

# Enable source maps for debugging
sourcemap = true

# Minify for production builds
minify = true

# Test configuration
[test]
# Enable coverage by default
coverage = true

# Coverage thresholds (90%+ enterprise requirement)
coverageThreshold = 90

# Skip test files in coverage reports
coverageSkipTestFiles = true

# Coverage reporters
coverageReporter = ["text", "json", "html", "lcov"]
