name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2 # v2
        with:
          bun-version: "1.2.0"

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: bunx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4.3.3

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: bun nx-cloud record -- echo Hello World
      - run: bun nx affected -t lint test build -- --coverage
      - name: Upload test artifacts (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nx-test-artifacts
          path: |
            **/test-results.xml  
            **/coverage/**
          retention-days: 7
      - name: Enforce coverage threshold
        if: always()
        run: |
          FILE=$(fd coverage-summary.json -a | head -n1 || true)  
          if [[ -f "$FILE" ]]; then  
            LINES=$(jq '.total.lines.pct' "$FILE")  
            echo "Lines coverage: $LINES%"  
            awk -v v="$LINES" 'BEGIN { if (v+0 < 90) exit 1 }'  
          else  
            echo "coverage-summary.json not found; skipping gate"  
          fi
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
